### ISSUE TITLE
problema nella replica in locale

### ISSUE THREAD

**Issue by orizzonti** [carlotafuro/Talk-LaravelDay-2022#1]
Ciao Carlo,
grazie per il tuo codice super interessante che hai presentato al laravelday 2022.
Stavo cercando di replicarlo in locale ma ho un problemino al momento del test (punto 2.3).
Premessa: sto cercando di far funzionare un progetto laravel che risponde a 2 domini differenti, uno laravel.sso.local e uno idp.sso.local... con l'idea poi di aggiungere altri domini.

Probabilmente mi sto "perdendo in un bicchiere d'acqua"... :)
Seguendo la tua guida ad un certo pounto dovrei testare il link http://idp.sso.local/module.php/core/authenticate.php?as=laravel-auth ... mi ritorna un 404 e mi sembra corretto: come fa a funzionare?
In effetti non c'è una rotta simile impostata. Forse mi sono perso io qualcosa?

Grazie mille.
Mario

**Comment by carlotafuro** [comment]
Ciao Mario,
accolgo con molto piacere il tuo apprezzamento per il lavoro fatto.

Parlare di rotta non è errato, ma in genere il termine è più calzante in un'applicazione Laravel.
Ho quindi il sospetto che tu stia facendo un po di confusione tra le due diverse applicazioni.
Da quanto ho capito dovresti avere **Laravel** dietro il virtual host http://laravel.sso.local/ e **SimpleSAMLphp** dietro http://idp.sso.local/

Se ricevi un errore 404 allora verifica la corretta installazione di SimpleSAMLphp al link http://idp.sso.local/module.php/sanitycheck/index.php che nel mio esempio corrisponde a https://idp.accomodati.it/module.php/sanitycheck/index.php

Prova anche a visualizzare un file statico, ad esempio http://idp.sso.local/resources/icons/ssplogo-fish-small.png
per essere sicuri che il virtual host sia configurato correttamente.

Se pensi che la mia guida sia poco chiara in qualche passaggio fammelo sapere e proverò a chiarirlo.

Aspetto un tuo riscontro per poi chiudere la issue.

Saluti
Carlo

**Comment by orizzonti** [comment]
Grazie della risposta Carlo.

In effetti stavo tentando di gestire il dominio idp.sso.local con la stessa identica applicazione laravel che risponde anche al dominio laravel.sso.local.

Quindi devo usare un'applicazione esterna per l'idp (e anche non laravel seguendo il tuo esempio).
Ok, ci riproverò. :O)

Intanto grazie e ancora grazie per la tua condivisione.

**Comment by carlotafuro** [comment]
Leggi con attenzione e sarà molto facile! Buon divertimento!!

**Comment by orizzonti** [comment]
Rieccomi Carlo 
:O)

Questa volta mi sono bloccato al punto 2.3, quando lancio l'indirizzo 
_/module.php/core/authenticate.php?as=laravel-auth_ 
vengo reindirizzato al 
_/module.php/core/frontpage_welcome.php_ 
con errore:
_ERR_TOO_MANY_REDIRECTS_

Forse sbaglio l'impostazione del virtual host? Però il file statico ( un file statico _/resources/icons/ssplogo-fish-small.png_) lo vedo correttamente.

Grazie....
